apiVersion: v1
kind: Config
clusters:
- name: development-playground
  cluster:
    proxy-url: http://proxy.example.org:3128
    server: https://k8s.example.org/k8s/clusters/c-xxyyzz
    certificate-authority: ca.crt
    certificate-authority-data: <base64 value of certificate>

users:
- name: developer
  user: 
    client-certificate: developer.crt
    client-key: developer.key

contexts:
- name: developer-development-playground
  context:
    cluster: development-playground
    user: developer
    namespace: dev