apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
    type: demo-rs
  annotations:
    buildversion: 1.2  
spec:
  template:
    metadata:
      name: <<pod-name>>
      labels:
        app: <<label-value>>
        type: <<label-value>>
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 2
  selector:
    matchLabels:
      type: demo-pod