apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: test.server.com
spec:
  scope: Namespaced
  group: test.server.com
  names:
    plural: testservers
    singular: testserver
    shortNames:
      - ac
    kind: TestServer
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openApiV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                from:
                  type: string
