apiVersion: v1
metadata:
  labels: 
    name: test-secrets-pod
kind: Pod
spec:
  containers:
    - name: test-secrets-container
      image: python
      # inject whole secret
      envFrom:
        - secretRef:
          name: test-secret
      # inject single env variable
      env:
        - name: test-env
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_PORT

  #Inject as a volume
  volumes:
    - name: app-secret-volumes
      secret:
        secretName: app-secret
        

