apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
    type: demo-rs
spec:
  template:
    metadata:
      name: <<pod-name>>
      labels:
        app: <<label-value>>
        type: <<label-value>>
    spec:
      containers:
        # multiple containers
        - name: nginx-container
          image: nginx
        - name: database-container
          image: mysql
  replicas: 2
  selector:
    matchLabels:
      type: demo-pod