apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp
spec:
  replicas: <Replicas>
  selector:
    app: myapp
  template:
    metadata:
      name: <<pod-name>>
      labels:
        app: <<label-value>>
        type: <<label-value>>
    spec:
      containers:
        # multiple containers
        - name: nginx-container
          image: nginx
        - name: database-container
          image: mysql
